[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "858181c542e9dc0e82d6d53f5142d815bc4588e5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[AMReX.download]]
    sha256 = "69101e56036ce6b30904e000153ab8666fe922ca1e5be2d5b66cfbe5032884f9"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "b223c8b49b37d8324de55e89697a45f1568a6d75"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[AMReX.download]]
    sha256 = "54d8b18aa063ae1a3df2053bcfa9e51ee59c1f18dccb6ce4742c2bce61bbc223"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "0ab0cfa1bd8abff9deb8d884befcb85a04d151b2"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[AMReX.download]]
    sha256 = "854fd1dc6b79738074aeaca6dce509c95cbf00c117e61f60209a259b6f958ef9"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d2af99df36c8b87c569e3af0f130acdfd033f92"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "f81918a8b72af12ad8f1e4043b74fa07fabdc0e4e719f714dda03583467f3647"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0b432151c7350e20e953f86c2aab1ff10695f4a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "722c4778401ade9e7046aed3653341a311d89607b8f8f60d7d994f39c44e840c"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e3b313dd7408e4add2a435707fa3bc90ed59e99"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "bd508b19e4277de5bbe2c2cf035daec81e0b83e1c25aa8d58a3fe7c37f303aef"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "6c5a5c0322353d811a2e9fdbea44bcb0c7ca0b74"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "da0c28c950c361d402a03dc7e5f6ba054f8d42e7b55daac7466c38df467ba1d4"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "5498a4ffdd7f5fd37911e1a922d2e572369bf2c5"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "c4dd5d0fb8f6f9a324c2490deb29342f4a8596d31e12dae121e0a81636bf32b9"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "142b0e51e39ecea996e48161610ea47a1a984450"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "d0594cb03ab6bf0b906d8b03e19667279f1cf03c794b20c547e5ac7de23b6d86"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "179a5b7f412cb2239f1e790624088bde9e4ac7dc"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "33fa8900b2925ddcc94728a5375835ac5023709902489cc1c8b9cd6b0d0a446a"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fde4786d19d8072bb7154a3778fd1fb448e3c0e4"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "ca09eb498794d88285c9e8fb9a4d23958608ef3dfcf8f4ebb9ee78e387888c40"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "396803b0f0ae9707333b272a33feaf3d135ec7cd"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "0b005435b105888d41ddcb2b4f3986f03cdf0f03f44cb3ec4652091ebcc1b100"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69735021fdb523495c3be3f3542468d05ac5c8e0"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "e3fd5841ea8445152284104d206c530dff13e76688b6669510ea335b5a24c98a"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0fbc4f256d7ba63f11e596587053ac4be5a4d8ae"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "b0adc33e2a300132e8841b387b10665d00771b5a623004c0e3562a715dd97fab"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0edb26218a17f5f4364f27e5145a3e9b828bbff5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "4a6ef6e2a18cd231885b5cbf676e933d0572ea5e80605480e168c7e36377d68e"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22de49ea6bed127e90f2825415e6af9ab5aa81b7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "2446a1db4b33ecf82e28a9d70645abae376a293707cee72ecc7e4f434f530689"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "486453bb7b9b7f6ce365763060fe36206e7ac38a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "844c57d67f28af2d1f06bc03e54dc6115d437323f7f2dfea4869aeb21b4bea0b"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.i686-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcebfef7acdd0f25f57c712b78fc5cc1636338c4"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[AMReX.download]]
    sha256 = "2346a54805028833c8f809d75f9ee3c0df80ead639a58c12fdc78f7d2bf89eb8"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.i686-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "94abdc2356918c38a195c040dd3111600cb1fac5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "b463cc706e1d4e6f65da3923f1589453ac139eb4e57534548ae85893b5dff534"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff4ccab92dbfee8c5532eee73086dc8e0bde286b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "63311a707969c5ec7b7fefdc994c781841a141b57eea97a6de715cf70e9c5c98"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f55543f2d1b75bbcc5d4e9bfb705fbc4fed6cadd"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "9d8048ae1013f8696056399f83bc2d2d3d5cef9abbeca255c8dd7ece7356ef65"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "01b79e910e0ee8672613097881b3488620106a92"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "9fc33d99ae1127513e6962e610c3cfe633023b46c3543d7abe92b075aec259ae"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5b0069814182a6ee75e421f788806dadf846afa"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "db6ee3ea6a615480aa2ce4256f9b76eacb0d6ffa66fb4657700c1001f971eda7"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "133c9df7af6b7bc642983936b993ef39f60de09d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "66f5898724deca8e3f7f232251fc5c8365dc0d91d7ecc030c3e0ba0d54a42d77"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "bc32a1ca89b758b1cdfc1d86dc86317e69e23d0d"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[AMReX.download]]
    sha256 = "528a963dcacccacf3c5f2a4e7f74488ac6f58d8b9db784e71ce8ddeb07ec8653"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "5d956adaa61d5a176998ceaef6d3d60914e50d54"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[AMReX.download]]
    sha256 = "4480cadc4183158abda5edc64f48dd93f18aa0115d5ef0afb64172518631ed0d"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "1eaa8bafdf273509710ed2329e49ef7284c4c4ee"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[AMReX.download]]
    sha256 = "0d8b94ac035906758aeab99b201fec76fa4cc9c26fcd5e6a3dcdeeda7d42b307"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "30aa71774bf866f5d37024aeb858e0171df2f160"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "b1e2d24dbc137ac53224e49b318379f376ce93823f911d4846338e7c60598329"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d017627a162dcb55ef99bf47a55e2dfdea09e18b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "d461cefef3e627f69b23981fb4df59a30f578d03392ef032bc7ebaeb4a20b417"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "334b664bb537f2870e68fa3ecda41fce0c685a23"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "871d3481614dafea68806d852b41bb043cb322d1346652cfa1da1c6e3d6e8ebd"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "278e6f227bdec19797c4d1adea7c835b90c14861"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "09c8c18033238ad296dd33fb7c62803275279ac3955dfe43d76a4672e6b150f1"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "43f7fce750f7ca29d9c569ae6476b2b2d8d61733"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "66d1fd3eb83b58292b73d159a8f0121e4d8cb338e0d4b1230249b552524eecc1"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "8ed0e977c1b278341d237d8fe0fa86b9e773c8b0"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "eafa9d0e3c7874f63d367964fc0574d0e37d2e2700767a490d33d9b0e14dfc09"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60216e3a671a3982736dafe118506a612a7d81a8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[AMReX.download]]
    sha256 = "87f8f2d80a2de5819c8e3a87870e6cc6805899f15913c34f246ad4e19a37485a"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.2.0+0/AMReX.v26.2.0.x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
