[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "c69920ba1e5d73440b4eb277a3edcb507bee9be8"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[AMReX.download]]
    sha256 = "82d9287c31ee59160283bec31c3964ea41a49b2d63db15518d7b07e11c1c53ec"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "7114f5bf9f35daeaf7d28e33f7ea15bd9bef594e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[AMReX.download]]
    sha256 = "f9633a4320d064ed306358e1c02e5998786b15dfa8a59d2cff6d5285db71716c"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "b4501762f65979c100d82228ed94f4271e26d9f7"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[AMReX.download]]
    sha256 = "b01c67aa978d15655300866f53cbbdea5d08f2444db594bd9d7eb38f0fc94fdb"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a487a57203d1e75e6b73a5aae56e0df147f2266e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "72f715292b8bb3568b038c2abeedd9d97c4d65eebba38dd2b5ede9844a41fb99"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06441e8d0949d4dcdcb9e0e6dd72ad49fb1ae278"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "982d28af03a077954338fa472ed2cf79fbdd2561cb2aa28b3d0ab7b031959c55"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5df28054163f619db1ee1fe3c245e9099753c8f"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "dd2528974ed0ec3c1eff167d7686b5572c091532d7c03a90293854f969ab1d00"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "8f41b7c3b5ce00b8f8d4ce8aada685ef801bd9c4"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "a7ec18c8b9bdf38c88969e96a40238a7670f559e3a644c779c43f9d78c437743"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "b75602fb7f63439914397c117cc83f7bea25f4ba"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "7a50f537871369f5bb8c987e325e7496a64242c7cef74c27e296494050d9f5d2"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "28ddccfba8af0dc712b7798fef79458bbe2c4f4e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "ead43050669f4b93920fc5c1a42f99fd250340171e522f0695121f497f4297ab"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "222fc5a35a4ce5b840a2d03871d01294628b86b3"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "bf911762e23097474c8f0994140fb2c2ab00f9f943f61f1db21e9fae77d05516"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "75160773dc9aa16aa994f6b480e3fcebd16cacba"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "e725aa9aa3601516f4050b9685dafafff5317d55b122d579472c157730c96259"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7bd144bbe30bb9fdf265587bc5c9a4bd2eeb3122"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "1157d1a75b599cf7ad5bb4511409e9ddf78f2fa7f50572df0065c312e27bb4ba"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "258a1ffe43a8f2e24c7c0e75e4e622e5681bcc7a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "0c088ddc515e61bb23f674094f018e28d0d965c6d548d01d22569c71a05540c0"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f466f356f0fb5a1da08bd1f5a68fbaa33bdbb58"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "af7e9dd8bef737679435ba6eb4b482fcd23b642aa1374977c6dfb6f48c6bf8d8"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "59028d74ea8effa6d258f798e04b1f4d58796b79"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "ec855dc59bd0cbd5eadbeb21e58eccb01928649f0b2d758d78e7756ea94237a4"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e1e4e42df141d29568df5f66ffa49e2ae7f87bb5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "cf5bf1eb8ad31dcce42d599b16ff403288909da4c4a2e7ed2088af24758e6297"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db26b2ee1dff4fb161c7c926245f2bf756672a2b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "ff4217e52423e4402480829ae40cd07e06df9b3769ec863b1ddcab8517a2b867"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.i686-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3e49b00cbf607e186ef90e785298908633b96f64"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[AMReX.download]]
    sha256 = "95d61ed25771024703e1a067b62abdc33618397ea2833564f3bf29ef35267ec0"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.i686-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6ac4390d1ef88ed85c752133a5188ab4cc96369"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "dd15e2995a8c137fa56b6aae930754ba17bf31ad945f8327415253a5e265b5a0"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "520ad9532ffd8b1fc7127ef4af39be5c3cce856c"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "ce74f825b71df4c5a88c351ac09adfb0632fd43e5680548ead572d82996e5856"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2cfeb9c8c268cf49b8babd0e435209bc35ec787b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "332e089b72d8dac323f41c04792d7bb7b1bade1e407abf62a4bd6d9b1d5fa566"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e4e07149ad74e6fb21afe882891a8e56cc53d1ec"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "07355de7d881232312355fd02e49839ede25fd46f71dde6188c8094d7a7ed82e"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c957c9ca4663d12c201b9dc91f4819fb79bcbcad"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "e5f183316b06d35240c72ef59ba569f8de072d9c13878e8af5fcd7d34f937193"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2f4d44e9fafef6739a2535437a70b245f63f68b"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "a49853c351959698fad5d8e0bfe582e81940e2201c6adf46848f4d21246144bf"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "4e285bb6ba7f842a8f4ee729161cdc65aa652077"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[AMReX.download]]
    sha256 = "28446032bb93c89582daefab44f55ea428c4f9a08b95f327f9f550b689b45e71"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "a3ee487623149971bb265e4c6c3397878779b3ba"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[AMReX.download]]
    sha256 = "0de071a3cb603f62af41b7e763f87463bab82d84bcdb5f4335f4e93a442c0037"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "c549de6e41381f95c6da336f19907aea8db1688d"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[AMReX.download]]
    sha256 = "f1dc271018d51a6d9e539ee1b42dc37b62e661109e452f470585b1bb01953fab"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56fedd98df1ac18a62c4c8a90ffcaf33cd3d4ffa"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "908af1c7fa41043333f984a33dbc45d7c059f021238ae785a85ae8a0fdb818db"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31ba98402f85d36d929284f7bc98e1d3feed0f8d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "8d8ec93d9be3596908a0d519a2b0c7793ed45a4438b6bb89f6abb8c2082a55eb"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4cf65eb36f60b3207760e7ebee1ff36ffaf7fb2a"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "b9e817669b0d27441b282a9dde426f66abcc3e9453c760b046812db5230c9281"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "a26c393b2c18335e8e6781314f07289fd24bf50e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "de67b88f3780470ba5dc8b59a370278f2aa72c3f9c630ecda7e094a3358b554c"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "44b1de1f4fbd95929faf733a6cc204b1118d6368"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "d6acbed5daaa88fcb2da565f809b29abc50a71cf59cf70960b2c6499cc1e951c"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "bf694cdc5f25eedc7db1d13a011a37e4419b485f"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "44645f345fd311ec051b72a380b9bcf136d558c2cddbca8684be7d62efda7521"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52c05bf4ddbb7811a3e3028bb48047535fa6bf5e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[AMReX.download]]
    sha256 = "a8c46578b5a719eac12c768128f270fcaa9bf550bed1ee7392277ec4c76d3ed6"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v25.11.0+0/AMReX.v25.11.0.x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
