[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "7a783748521f8c77b78dfae7af844acce02f7a73"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[AMReX.download]]
    sha256 = "5fcdb5a0561e85c1ae25da1eebe01d1c51efe5219d8fd3af79a1abbc9ae54f0a"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "124687d104aa9c3854de74ad11d6e0783d719968"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[AMReX.download]]
    sha256 = "7e86bb490ea897d6fe4800e8b33066c051f19228a14da19feac09585df83de2b"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "4b613aa3b86370763d6116bb1f0d2651b316717e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[AMReX.download]]
    sha256 = "a5a9381cde737567a909f30c880f45f01b1ea57c2be48c96fdeaab4269e6b3cc"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a04ab4b86806f8bc23d5f3927f93c4f8ba9a6d2e"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "a7d3f203ef234281d9a20fd7f8bc162ff6bc342422d5ff5e10241454c7523235"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e878363faf7a406c983196ef9a207316fbc63fa"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "c3a6ea3e15df1fc056e93746346344d74e1d8af644544498579594bef3aaab53"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "aa55409cb7318a606581e5a89d3ad6e72ffe7aed"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "35bb1663853a02013b57ac0a69d488d1987134c9b99cdd73430a91ac7292eb36"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "792d634f9b79389a35501cd087b8d3cdc74bd547"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "c0a25be90aaf1c2463161f65a89ee9de3b765dfda73a2b760ffe6456369a5bfc"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "df73d686453e852271a11ece33f2e745cee91fa6"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "088333762ce2f60464d340a77ce10dbe3f3b08b130e7c5ee6a327e33ac7d0ea3"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "aarch64"
git-tree-sha1 = "29230b678c4aa4e29aa09b2f66dd8d8dbccd2e45"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "f4cddb8047a8cc40c378b715c2c5400eb1cea9e744064522371573c0d3309023"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.aarch64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff2c0c6b5bdbf6a3a5b97104109102e1c5eadc0d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "ca7f25695ca7308a6259813b819070d353633e7fe9b515310567d753d7922b19"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "20df7cec47557ecf2773accb10469232f18cb3b8"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "202f14265c4750a46bb9d5959854d9805b63f539278e6a9350e7401a1ef7cc1a"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.armv6l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "23adf94e6248e2a6569e06b36beb2a07fd451c4d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "dd4e819144a9d45eac46fd09480debf2f412a9614f1e6f09e6e6e6ad02eb924d"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f00fe5aeca606ba0808dc0436128eb9f33f3e9b3"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "9e020291fe8935ebd4aa6e57f6ed736443911d47c7125394effe6941d9dcf559"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d6786313dabe47eee279af3980714fc65daf9c59"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "c7bd5624fbd2123bd017fe9821b2c2d316eb3c33f4f21b097c73e22731dfb47a"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.armv7l-linux-gnueabihf-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef10f43839cccaca1888f9a0543d9646853224f7"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "3307240a625049ced98bf5258d20acf412984cb36bfe29fac2102972fe9ae607"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "10295043dddb4742b6ae331844be6d2cbe7268e5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "87cf2da00203d28bafbc1d75bd893722a2448e8b4cbfa5cea45a897f92f0e601"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.i686-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f5db7fddf8f6c5625a06539eccb1f2f7c5a58bf2"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "01ad11294044065fac8e9ac0d29707a822a31ab84ce1cf09f8adb9efc13540ea"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.i686-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ee4356abf9de4dd0dff638f417c528c38e96718e"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[AMReX.download]]
    sha256 = "ba5e17687c9dfba0ee90951f65e493156b3773f32349e9e72d55a584b80e2413"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.i686-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "483a1f5adf380cf1ab406aa45997ca02dae825a5"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "e550d39cbc1e4d9d46fa1cd7cea55ac0af4607f452750adcdbb23ef288a3c3af"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "48b596e8c2cf30f8480ea4dc0e5a766de47e099d"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "563e274578428fdbb57947c1f3a590d0db2437d9f073ffc2ddbd7ea7432bd8a5"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9b7112bc0dae3467fd997e3af77e0be91932c32"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "3021f7c825fda1c17a07c9e7553519b2abfe55626fa74e02a508ac9965f7847b"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.powerpc64le-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ea912d3b48734cc7bc41c676d375e0d93a09c505"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "676d8c62416256be47492d292c67797687a51b9208586cc0f1de7209bf5574e5"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8c38cf895f8eee0354cd404a5dcd6f842dfc6fd6"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "f9012df20c4bb6e9415ac00d2c10013f3919341ffcb6815c5f6a39539c7738d5"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b662e34ec01c24d83453a60649dabd3a059c18a4"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "e3b91f99aa98f769a904a57658376d131bc2a9759ffa0363c9b9064bb0acd487"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.riscv64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "88634ae9f4d27904c1ccd6bd17c721c99b6cd72b"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[AMReX.download]]
    sha256 = "1f6c136a325f0466743c8be2f371db3099c49ec3171331d78a3021219976063f"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "78c38195ed7aee61f0276ee3fde01409168c6c91"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "macos"

    [[AMReX.download]]
    sha256 = "9df26ecc7b504f1a059aeb98968f9ffacab0cd995e76f3b36ebbe70bd5e961bf"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-apple-darwin-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "df6694f83267f348bd5a9d6e8cb74461635572cd"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "macos"

    [[AMReX.download]]
    sha256 = "ce0aac3c0ad768d4c5a5f49bc5b14218e0b1b02f43f0e248d3909fec80c21e6c"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-apple-darwin-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a099a1fe73835a3afab0ca8a16bc071bd9bf703"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[AMReX.download]]
    sha256 = "24c6eb8511513933de011964204786c9e287222715bd03baa27c562ecdd4544c"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7eed3f5e7a96df89d4f08096ed0b21dc37410a18"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[AMReX.download]]
    sha256 = "359a35a0e16944b1dfe998a6a2e875151c268af65e4ee9e874feaa8681fa2aa5"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5911962b47ac6062b217c4758cca76e0cd0b3ed"
lazy = true
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[AMReX.download]]
    sha256 = "2d54c69a8228714bdf711795e061e03c2b5869e64aa2311efe57f35f96f4c809"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "9048b1cdc6f47ce73f81949e91501a0661b2a8e6"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "c280a88e84728c989cd27de0e96029af75b0f822930dcc40882f516f97076ba5"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpich.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "c33d93b3018f8c466a88e09577b3939df2b13a42"
lazy = true
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "3bb9a7bb1d2776739b4025948b943dd24a28e7f40948b13c5f42dba7961cc1ad"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-unknown-freebsd-libgfortran5-mpi+mpitrampoline.tar.gz"
[[AMReX]]
arch = "x86_64"
git-tree-sha1 = "b0fec213f8d173f4577778858aa9a6757fdf028d"
lazy = true
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "freebsd"

    [[AMReX.download]]
    sha256 = "bb50efeeb97dd1c18e783075bd2bb846701ab1d6e78e79db2219222cc2376978"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-unknown-freebsd-libgfortran5-mpi+openmpi.tar.gz"
[[AMReX]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c93fa9682ea2100132275a2a72fcb56834e0330f"
lazy = true
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[AMReX.download]]
    sha256 = "22cb614c299b0ee9297ad757f3351d158bdf271f099d17084bb20c87c3e8d2cc"
    url = "https://github.com/JuliaBinaryWrappers/AMReX_jll.jl/releases/download/AMReX-v26.1.0+0/AMReX.v26.1.0.x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi.tar.gz"
